import { defineStore } from 'pinia'

export const useGlobalStore = defineStore({
  id: 'globalStore',
  state: () => ({
    count: 0,
    name: 'Cch',
    EvaluationIcon: [
      'i-streamline-emojis-amazed-face',
      'i-streamline-emojis-anxious-face',
      'i-streamline-emojis-anguished-face',
      'i-streamline-emojis-anxious-face',
      'i-streamline-emojis-astonished-face',
      'i-streamline-emojis-beaming-face-with-smiling-eyes',
      'i-streamline-emojis-confounded-face',
      'i-streamline-emojis-confused-face',
      'i-streamline-emojis-crazy-face',
      'i-streamline-emojis-crying-face',
      'i-streamline-emojis-determined-face',
      'i-streamline-emojis-disappointed-face',
      'i-streamline-emojis-dizzy-face',
      'i-streamline-emojis-downcast-face-with-sweat',
      'i-streamline-emojis-drooling-face-1',
      'i-streamline-emojis-drooling-face-2',
      'i-streamline-emojis-expressionless-face',
      'i-streamline-emojis-face-blowing-a-kiss',
      'i-streamline-emojis-face-savoring-food',
      'i-streamline-emojis-face-screaming-in-fear',
      'i-streamline-emojis-face-vomiting',
      'i-streamline-emojis-face-with-head-bandage',
      'i-streamline-emojis-face-with-medical-mask',
      'i-streamline-emojis-face-with-monocle',
      'i-streamline-emojis-face-with-raised-eyebrow',
      'i-streamline-emojis-face-with-rolling-eyes',
      'i-streamline-emojis-face-with-steam-from-nose',
      'i-streamline-emojis-face-with-symbols-on-mouth',
      'i-streamline-emojis-face-with-thermometer',
      'i-streamline-emojis-face-without-mouth',
      'i-streamline-emojis-fearful-face',
      'i-streamline-emojis-flushed-face',
      'i-streamline-emojis-frowning-face',
      'i-streamline-emojis-full-moon-face',
      'i-streamline-emojis-grimacing-face',
      'i-streamline-emojis-grinning-face',
      'i-streamline-emojis-grinning-face-with-smiling-eyes',
      'i-streamline-emojis-grinning-face-with-sweat',
      'i-streamline-emojis-grinning-squinting-face',
      'i-streamline-emojis-kissing-face-with-closed-eyes',
      'i-streamline-emojis-hushed-face-1',
      'i-streamline-emojis-hushed-face-2',
      'i-streamline-emojis-neutral-face',
      'i-streamline-emojis-money-mouth-face-1i-streamline-emojis-money-mouth-face-1',
      'i-streamline-emojis-money-mouth-face-2',
      'i-streamline-emojis-persevering-face',
      'i-streamline-emojis-pensive-face',
      'i-streamline-emojis-relieved-face-2',
      'i-streamline-emojis-relieved-face-1',
      'i-streamline-emojis-slightly-smiling-face',
      'i-streamline-emojis-smiling-face-with-heart-eyes',
      'i-streamline-emojis-smirking-face',
      'i-streamline-emojis-smiling-face-with-smiling-eyes',
      'i-streamline-emojis-smiling-face-with-sunglasses',
      'i-streamline-emojis-sneezing-face',
      'i-streamline-emojis-thinking-face',
      'i-streamline-emojis-star-struck-1',
      'i-streamline-emojis-star-struck-2',
      'i-streamline-emojis-tired-face',
      'i-streamline-emojis-unamused-face',
      'i-streamline-emojis-upside-down-face',
      'i-streamline-emojis-weary-face-2',
      'i-streamline-emojis-winking-face',
      'i-streamline-emojis-worried-face',
      'i-streamline-emojis-worried-face',

      'i-streamline-emojis-squinting-face-with-tongue',
      'i-streamline-emojis-rolling-on-the-floor-laughing-2',
    ],
    food: [
      'i-streamline-emojis-hamburger-3',
      'i-streamline-emojis-honey-pot',
      'i-streamline-emojis-hot-beverage-2',
    ],
    fruit: [
      'i-streamline-emojis-peach',
      'i-streamline-emojis-pear',
      'i-streamline-emojis-cherries',
      'i-streamline-emojis-red-apple',
      'i-streamline-emojis-strawberry-1',
      'i-streamline-emojis-lemon',
    ],
  }),
  getters: {
    doubleCount: (state) => state.count * 2,
    peopleIcons: (state) => state.EvaluationIcon,
  },
  actions: {
    increment() {
      this.count++
    },
  },
  persist: {
    key: 'globalStore',
  },
})
